default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: db/development.sqlite3


# development:
#   adapter: postgresql
#   encoding: unicode
#   pool: 5
#   database: postgres
#   url: "postgresql://notesdb.shefpaas:5432"
#   username: postgres
#   password: password

# test:
#   adapter: postgresql
#   encoding: unicode
#   pool: 5
#   database: postgres
#   url: "postgresql://notesdb.shefpaas:5432"
#   username: postgres
#   password: password
#
# production:
#   adapter: postgresql
#   encoding: unicode
#   pool: 5
#   database: postgres
#   url: "postgresql://notesdb.shefpaas:5432"
#   username: postgres
#   password: password
