# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Department.delete_all
Department.create(name: 'Archaeology')
Department.create(name: 'English')
Department.create(name: 'History')
Department.create(name: 'Languages & Cultures')
Department.create(name: 'Music')
Department.create(name: 'Philosophy')
Department.create(name: 'Control & Systems Engineering')
Department.create(name: 'Aerospace Engineering')
Department.create(name: 'Bioengineering')
Department.create(name: 'Civil Engineering')
Department.create(name: 'Computer Science')
Department.create(name: 'Chemical Engineering')
Department.create(name: 'Electronic & Electrical Engineering')
Department.create(name: 'Engineering Materials')
Department.create(name: 'Mechanical Engineering')
Department.create(name: 'Dentistry')
Department.create(name: 'Human Communication Science')
Department.create(name: 'Medicine')
Department.create(name: 'Nursing & Midwifery')
Department.create(name: 'Ophth. & Orthoptics')
Department.create(name: 'Animal & Plant Science')
Department.create(name: 'Biomedical Science')
Department.create(name: 'Chemistry')
Department.create(name: 'Mathematics & Stats')
Department.create(name: 'Molecular Biology & Biotech')
Department.create(name: 'Physics & Astronomy')
Department.create(name: 'Psycology')
Department.create(name: 'Architecture')
Department.create(name: 'East Asian Studies')
Department.create(name: 'Economics')
Department.create(name: 'Education')
Department.create(name: 'Geography')
Department.create(name: 'Journalism')
Department.create(name: 'Law')
Department.create(name: 'Landscape')
Department.create(name: 'Management')
Department.create(name: 'Politics')
Department.create(name: 'Sociological Studies')
Department.create(name: 'Urban Planning')
Department.create(name: 'Lifelong Learning')
